sudo: required
services:
  - docker
before_install:
  - docker build -t asish61/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run asish61/react-test npm test -- -- coverage

after_success:
  - docker build -t asish61/multi-client ./client
  - docker build -t asish61/multi-nginx ./nginx
  - docker build -t asish61/multi-server ./server
  - docker build -t asish61/multi-worker ./worker

  #Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub

  - docker push asish61/multi-client
  - docker push asish61/multi-nginx
  - docker push asish61/multi-server
  - docker push asish61/multi-worker